language: c

sudo: no

install:
  - |
    if [[ ! -e "$nim_bin_path/nim" ]]
       #Build nim if it doesnt exist
    then
        curl -sSL -O "http://nim-lang.org/download/nim-$nim_version.tar.xz"
        tar xvJf "nim-$nim_version.tar.xz"
        cd "nim-$nim_version"
        sh build.sh
        bin/nim c koch
        ./koch boot -d:release
        cd ..
    fi
    if [[ ! -e "$texinfo_bin_path/texi2any" ]]
       #Build makeinfo if doesnt exist
    then
        curl -sSL -O "http://ftp.gnu.org/gnu/texinfo/texinfo-$texinfo_version.tar.gz"
        tar xvzf texinfo-$texinfo_version.tar.gz
        cd texinfo-$texinfo_version
        ./configure && make -j2
        cd ..
    fi
    if [[ ! -e "$nre_lib_path/nre.nim" ]]
       #Import nre with built it pcre if doesnt exist
    then
        git clone https://github.com/flaviut/nre
    fi

cache:
  directories:
    - nim-0.13.0
    - texinfo-6.0
    - nre

before_script:
  - export PATH="nim-0.13.0/bin${PATH:+:$PATH}"

env:
  - texinfo_version=6.0 travis_build_home="/home/travis/build/Lompik/nim-doc" texinfo_bin_path="$travis_build_home/texinfo-$texinfo_version/tp" nre_lib_path="$travis_build_home/nre/src" nim_version=0.13.0 nim_bin_path="$travis_build_home/nim-$nim_version/bin" nim_lib_path="$travis_build_home/nim-$nim_version/lib"

matrix:
  fast_finish: true

script:
  - echo $PWD
  - /home/travis/build/Lompik/nim-doc/build.sh

notifications:
  email: false
