language: c

sudo: no

addons:
  apt:
    packages:
    - texinfo

install:
  - |
    if [[ ! -e "nim-$nim_version/bin/nim" ]]
       #Build nim if it doesnt exist
    then
        curl -sSL -O "http://nim-lang.org/download/nim-$nim_version.tar.xz"
        tar xvJf "nim-$nim_version.tar.xz"
        cd "nim-$nim_version"
        sh build.sh
        bin/nim c koch
        ./koch boot -d:release
        cd ..
    fi
    if [[ ! -e "pcre" ]]
       #Build makeinfo if doesnt exist
    then
        curl -sSL -O "ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-$pcre_version.tar.gz"
        tar xvzf pcre-$pcre_version.tar.gz
        [[ ! -d pcre ]] && mkdir pcre
        cd pcre-$pcre_version
        ./configure --prefix=$PWD/../pcre && make -j2 && make install
        cd ..
        ln -s pcre/lib/libpcre.so.1 pcre/lib/libpcre.so.3
    fi

cache:
  directories:
    - nim-0.13.0
    - pcre

before_script:
  - export PATH="$PWD/nim-0.13.0/bin${PATH:+:$PATH}"

env:
  - pcre_version=8.38 nim_version=0.13.0

matrix:
  fast_finish: true

script:
  - echo $PWD
  - /home/travis/build/Lompik/nim-doc/build.sh

notifications:
  email: false
