language: c

sudo: no

install:
  - |
    if [[ ! -e "nim-$nim_version/bin/nim" ]]
       #Build nim if it doesnt exist
    then
        curl -sSL -O "http://nim-lang.org/download/nim-$nim_version.tar.xz"
        tar xvJf "nim-$nim_version.tar.xz"
        cd "nim-$nim_version"
        sh build.sh
        bin/nim c koch
        ./koch boot -d:release
        cd ..
    fi
    if [[ ! -e "texinfo-$texinfo_version/tp/texi2any" ]]
       #Build makeinfo if doesnt exist
    then
        curl -sSL -O "http://ftp.gnu.org/gnu/texinfo/texinfo-$texinfo_version.tar.gz"
        tar xvzf texinfo-$texinfo_version.tar.gz
        cd texinfo-$texinfo_version
        ./configure && make -j2
        cd ..
    fi
    if [[ ! -e "nre/src/nre.nim" ]]
       #Import nre with built it pcre if doesnt exist
    then
        git clone https://github.com/flaviut/nre
    fi

cache:
  directories:
    - nim-0.13.0
    - texinfo-6.0
    - nre

before_script:
  - export PATH="nim-0.13.0/bin${PATH:+:$PATH}"

env:
  - texinfo_version=6.0 nim_version=0.13.0

matrix:
  fast_finish: true

script:
  - echo $PWD
  - /home/travis/build/Lompik/nim-doc/build.sh

notifications:
  email: false
